Feature/aaron kirk/login page and screen header
TritonSE/LAK-Goods-Transport-Application pull request #11
Opened 2022-01-18 02:09 UTC by aaron-kirk

### Adminstrative Info
[Github Issue #4 ]

### Changes
What changes did you make?
- Implemented `ScreenHeader` component with optional back button
- Merged and made small styling changes to Aman's components (to better match Figma); have not discussed this with him, though
- Implemented Login Page content using Aman's `LabelWrapper` component

### Testing
How did you confirm your changes worked?
- Loaded screen on Pixel 4 Emulator
- Clicked on buttons to ensure prints were coming through
- Tried the `ScreenHeader` with and without arrow

### Confirmation of Change
Upload a screenshot, if possible. Othwerwise, please provide instructions on how to see the change.

https://youtu.be/SpQ9gskzaCs

2022-01-20 02:26 UTC, AmanKAggarwal commented
Agreed with changes to `PrimaryButton` and `LabelWrapper`

2022-01-20 07:22 UTC, doraemon127 requested changes
lgtm,, maybe discuss styling changes to Aman's components with Aman before merging

2022-01-20 07:24 UTC, doraemon127 approved these changes
wait sorry I just saw that Aman already agreed with the changes.

2022-01-25 00:03 UTC, NirmalAgnihotri approved these changes

2022-01-25 00:03 UTC, NirmalAgnihotri commented on LAKMobile/src/screens/LoginScreen.tsx
> +    input: {
Brought this up in Aman and Assaf's pr, but since these inputs are shared this could potentially be moved outside since other pages may need it.

2022-01-25 00:05 UTC, NirmalAgnihotri commented
Awesome work! Good job syncing up with Aman and Assaf's code

2022-01-27 03:58 UTC, merged